### ISSUE TITLE
createTransactionResult not working with Truffle v5

### ISSUE THREAD

**Issue by ei08047** [rkalis/truffle-assertions#5]
web3 : 1.0.0-beta.36
truffle : 5.0@next
ganache
____
createTransactionResult
TypeError: allEvents.get is not a function
____

tried allEvents.on("data", data =>{} )  but could not catch Event launched from constructor..

**Comment by rkalis** [comment]
Hi @ei08047 

Thanks for opening this issue. Could you provide the parameters you are passing to the parameter. If it is possible, could you also add some code snippets of the full context where you are calling the function. That way I can better see what is happening.

**Comment by rkalis** [comment]
@ei08047 @andrewgordstewart Thanks for providing more context to this problem. 

I published a new version of `truffle-assertions` with support for both web3 0.x / Truffle v4 and web3 1.x / Truffle v5. The issue should be fixed, but let me know if you still experience issues with this.

Additionally, I am working on a 1.0 release for `truffle-assertions`, which will only officially support the new web3 1.x / Truffle v5. Version 0.x of `truffle-assertions` will remain available for projects using web3 0.x / Truffle v4.
